title: "seophohoho 기술 블로그"
email: seophohoho@gmail.com
description: >-
baseurl: ""
url: "https://seophohoho.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
author:
  name: "seophohoho"
  github: "seophohoho"

# Pagination
paginate: 10          # <-- 2. 여기서 숫자를 조절합니다. (예: 6개씩 보이기)
paginate_path: "/page:num/"